
name: WakaTime Metrics

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: tw93/wakatime-charts@master
        with:
          BRANCH_NAME: main
          COMMIT_MESSAGE: wakatime-bot > WakaTime has been updated.
          IMAGES_FOLDER: images
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }} # only required if using the action in repository other than profile
